### ISSUE TITLE
Container won't start with local Dockerfile: exec: "ssh-mock": executable file not found

### ISSUE THREAD

**Issue by bwest937** [DanielHabenicht/mock-ssh#1]
When using the local Dockerfile, the ssh-mock command didn't work:

```
Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "ssh-mock": executable file not found in $PATH: unknown
```

Fixed by updating the VERSION arg to current version 0.3.1:

```
    build:
      context: .
      args:
        - VERSION=0.3.1
```

Thanks for a cool thing.
